In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'text':['People watch campusx','campusx watch campusx','people write comment','campusx write comment'],'Output':[1,1,0,0]})

In [ ]:
df

text  Output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

Bag Of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()   #Read more sklearn.feature_extraction.text.countVectorizor

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
#vocab
vocab = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [ ]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

N-Grams

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))   #Bigrams
cv1 = CountVectorizer(ngram_range=(3,3))  #Trigrams
cv2 = CountVectorizer(ngram_range=(1,2))  #Both Unigram and Bigram
cv3 = CountVectorizer(ngram_range=(1,3))

In [ ]:
bigram = cv.fit_transform(df['text'])
Trigram = cv1.fit_transform(df['text'])
uniBigram = cv2.fit_transform(df['text'])
abc=cv3.fit_transform(df['text'])

['People watch campusx','campusx watch campusx','people write comment','campusx write comment']

In [ ]:
#vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [ ]:
print(cv1.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [ ]:
print(cv2.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [ ]:
print(cv3.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}
